### ISSUE TITLE
PySCF converter fails with 'cc-pvdz'

### ISSUE THREAD

**Issue by scemama** [TREX-CoE/trexio_tools#42] opened 2024-11-06 09:30 UTC
This script works with the 6-31g basis, but fails with cc-pvdz:

```python
from pyscf import gto, scf
from pyscf.lib import chkfile

import os

mol = gto.Mole()
mol.atom = 'H 0 0 0; F 0 0 1.1'
mol.basis = 'cc-pvdz'
mol.build()

mf = scf.RHF(mol)
mf.chkfile = 'rhf.chk'
mf.kernel()

filename = 'rhf.hdf5'
os.remove(filename)
os.system('trexio convert-from -t pyscf -i rhf.chk -b hdf5 '+filename)
```

```bash
$ python test3.py
converged SCF energy = -99.9873974403488
/home/scemama/miniconda3/lib/python3.10/site-packages/pyscf/dft/libxc.py:772: UserWarning: Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, the same to the B3LYP functional in Gaussian and ORCA (issue 1480). To restore the VWN5 definition, you can put the setting "B3LYP_WITH_VWN5 = True" in pyscf_conf.py
  warnings.warn('Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, '
Traceback (most recent call last):
  File "/home/scemama/miniconda3/bin/trexio", line 8, in <module>
    sys.exit(main())
  File "/home/scemama/TREX/trexio_tools/src/trexio_tools/trexio_run.py", line 95, in main
    run(args["TREXIO_FILE"], args["--input"], args["--type"], back_end=back_end, motype=args["--motype"])
  File "/home/scemama/TREX/trexio_tools/src/trexio_tools/converters/convert_from.py", line 779, in run
    run_pyscf(trexio_filename=trexio_filename, pyscf_checkfile=filename, back_end=back_end_str)
  File "/home/scemama/TREX/trexio_tools/src/trexio_tools/converters/pyscf_to_trexio.py", line 215, in pyscf_to_trexio
    basis_coefficient.append(float(bas_ctr_coeff))
TypeError: only length-1 arrays can be converted to Python scalars
```

From the error message, I suppose that the basis is in the generalized contraction format (one set of exponents and multiple sets of coefficients, like molpro and molcas).

**Comment by q-posev** [comment] 2024-11-06 12:48
@scemama @kousuke-nakano  does this happen if you produce TREXIO directly from PySCF using the recently implemented functionality (see [this PR](https://github.com/pyscf/pyscf-forge/pull/60)) ?

**Comment by NastaMauger** [comment] 2024-11-07 04:05
Hello,

I also had this issue with this basis set/TREXIO using the latest PySCF (2.7.0)

Best

**Comment by kousuke-nakano** [comment] 2024-11-07 10:04
@NastaMauger, Thank you for your report. I am investigating it.

**Comment by scemama** [comment] 2024-11-07 15:46
@kousuke-nakano I am using PySCF 2.3.0

**Comment by kousuke-nakano** [comment] 2024-11-08 06:29
Dear @scemama and @NastaMauger 

I have pinpointed the problem. As you expected, one set of exponents and multiple sets of coefficients.

For instance, the all-electron `cc-pVDZ` basis sets for H and F in the nwchem format are:

> BASIS "ao basis" SPHERICAL PRINT
> #BASIS SET: (5s,2p) -> [3s,2p]
> H    S
>       1.301000E+01           1.968500E-02           0.000000E+00
>       1.962000E+00           1.379770E-01           0.000000E+00
>       4.446000E-01           4.781480E-01           0.000000E+00
>       1.220000E-01           5.012400E-01           1.000000E+00
> H    S
>       0.0297400              1.0000000
> H    P
>       7.270000E-01           1.0000000
> H    P
>       0.1410000              1.0000000
> #BASIS SET: (10s,5p,2d) -> [4s,3p,2d]
> F    S
>       1.471000E+04           7.210000E-04          -1.650000E-04           0.000000E+00
>       2.207000E+03           5.553000E-03          -1.308000E-03           0.000000E+00
>       5.028000E+02           2.826700E-02          -6.495000E-03           0.000000E+00
>       1.426000E+02           1.064440E-01          -2.669100E-02           0.000000E+00
>       4.647000E+01           2.868140E-01          -7.369000E-02           0.000000E+00
>       1.670000E+01           4.486410E-01          -1.707760E-01           0.000000E+00
>       6.356000E+00           2.647610E-01          -1.123270E-01           0.000000E+00
>       1.316000E+00           1.533300E-02           5.628140E-01           0.000000E+00
>       3.897000E-01          -2.332000E-03           5.687780E-01           1.000000E+00
> F    S
>       0.0986300              1.0000000
> F    P
>       2.267000E+01           4.487800E-02           0.000000E+00
>       4.977000E+00           2.357180E-01           0.000000E+00
>       1.347000E+00           5.085210E-01           0.000000E+00
>       3.471000E-01           4.581200E-01           1.000000E+00
> F    P
>       0.0850200              1.0000000
> F    D
>       1.640000E+00           1.0000000
> F    D
>       0.4640000              1.0000000
> END

which are internally stored in `pyscf` as:

```
>>> import numpy as np
>>> import pyscf
>>> mol = pyscf.M(atom='H 0 0 0; F 0 0 1', basis='ccpvdz', cart=False)

>>> mol._bas
array([[ 0,  0,  3,  1,  0, 64, 67,  0],
       [ 0,  0,  1,  1,  0, 70, 71,  0],
       [ 0,  1,  1,  1,  0, 72, 73,  0],
       [ 1,  0,  8,  2,  0, 28, 36,  0],
       [ 1,  0,  1,  1,  0, 52, 53,  0],
       [ 1,  1,  3,  1,  0, 54, 57,  0],
       [ 1,  1,  1,  1,  0, 60, 61,  0],
       [ 1,  2,  1,  1,  0, 62, 63,  0]], dtype=int32)

>>> coeff = np.hstack([mol.bas_ctr_coeff(i).ravel() for i in range(mol.nbas)])
>>> coeff
array([ 3.34987264e-02,  2.34800801e-01,  8.13682958e-01,  1.00000000e+00,
        1.00000000e+00,  7.20673709e-04, -3.21193890e-04,  5.55048697e-03,
       -2.54619157e-03,  2.82542077e-02, -1.26433595e-02,  1.06395828e-01,
       -5.19574917e-02,  2.86684201e-01, -1.43447138e-01,  4.48437966e-01,
       -3.32437623e-01,  2.64641181e-01, -2.18659068e-01,  1.53260610e-02,
        1.09559041e+00,  1.00000000e+00,  6.48340215e-02,  3.40535360e-01,
        7.34646407e-01,  1.00000000e+00,  1.00000000e+00])
>>> len(coeff)
27
>>> exps = np.hstack(mol.bas_exps()) = np.hstack(mol.bas_exps())
>>> exps
array([1.301e+01, 1.962e+00, 4.446e-01, 1.220e-01, 7.270e-01, 1.471e+04,
       2.207e+03, 5.028e+02, 1.426e+02, 4.647e+01, 1.670e+01, 6.356e+00,
       1.316e+00, 3.897e-01, 2.267e+01, 4.977e+00, 1.347e+00, 3.471e-01,
       1.640e+00])
>>> len(exps)
19

```
where the 4th column of `mol._bas` represents how many coefficient sets share an exponential set.

Let's denote `num_of_shell` = `np.sum(mol._bas[:, 3])` and `num_of_reduced_shell` = `len(mol._bas)`. `num_of_shell` = 9 and `num_of_reduced_shell`= 8.

The problem is that the shape of the obtained MOs is compatible with `num_of_reduced_shell`, not with `num_of_shell`. So, we cannot store them in a TREXIO file.

A workaround could be to switch off the general contraction. I am investigating how to do it. If you find it, please let me know.

note: `ccecp-ccpVXZ` basis works.

**Comment by kousuke-nakano** [comment] 2024-11-08 06:48
See this [PR](https://github.com/pyscf/pyscf-forge/pull/68#issuecomment-2463900265).

**Comment by scemama** [comment] 2024-11-08 09:48
@kousuke-nakano We just need to replicate the exponents for each set of coefficients:
This
```
F P
2.267000E+01 4.487800E-02 0.000000E+00
4.977000E+00 2.357180E-01 0.000000E+00
1.347000E+00 5.085210E-01 0.000000E+00
3.471000E-01 4.581200E-01 1.000000E+00
```
becomes this
```
F P
2.267000E+01 4.487800E-02 
4.977000E+00 2.357180E-01 
1.347000E+00 5.085210E-01 
3.471000E-01 4.581200E-01 
F P
2.267000E+01 0.000000E+00
4.977000E+00 0.000000E+00
1.347000E+00 0.000000E+00
3.471000E-01 1.000000E+00
```
Is it possible to do it by manipulating the internal format of PySCF?
Somethig like:
```python
exponents = []
coefficients = []
for shell in pyscf_shells:

  # Loop over the sets contraction coefficients (columns of coefficients)
  for coefs in pyscf_coefs[shell]: 

    # Append the exponents (common to all contractions)
    exponents += pyscf_exponents[shell]

    # Append the coefficients (specific to the contraction)
    coefficients += coefs
```

**Comment by q-posev** [comment] 2024-11-09 09:13
Could it be again the question of cartesian vs spherical basis? I recall that in GAMESS for example, the 6-31g basis is used with cartesian functions but Dunning basis sets like cc-pvXz require spherical harmonics.

**Comment by kousuke-nakano** [comment] 2024-11-09 10:38
Dear @scemama, yes, I agree. If one can do it, the problem is solved. However, the internal structure of `pyscf` is a bit complicated and entangled, so I am not sure how to do it. Let's wait for a reply from a `pyscf` developer. See this [PR](https://github.com/pyscf/pyscf-forge/pull/68#issuecomment-2463900265).

**Comment by q-posev** [comment] 2024-11-09 19:09
@kousuke-nakano found this [discussion in PySCF repo](https://github.com/pyscf/pyscf/issues/2431). Not sure if it's useful here but something to keep in mind regarding their approach to normalization.

**Comment by NastaMauger** [comment] 2024-11-10 23:25
There are missing data (AO shell and AO normalization) in the TREXIO file, which is preventing the import of TREXIO when using pyscf-forge code. See [here](https://github.com/pyscf/pyscf-forge/pull/80#issuecomment-2466983271l)

**Comment by kousuke-nakano** [comment] 2024-11-11 02:18
Dear @NastaMauger, Thanks for your report. Yes, we are now discussing the differences in the notations of `AO shell` and `AO normalization` between `TREXIO` and `PySCF`. Once they are clear, I will finish the built-in `TREXIO` converter in `pyscf-forge` asap. Would you wait for a while?

**Comment by NastaMauger** [comment] 2024-11-11 02:21
Dear @kousuke-nakano, no worries! I just couldn’t find any issues or information related to what I discovered. I might have overlooked it, so I wanted to write it down to make sure the information isn’t lost.

**Comment by q-posev** [comment] 2024-11-13 08:18
Closing this issue here and moving all related to discussion to `pyscf-forge` [here](https://github.com/pyscf/pyscf-forge/issues/82) (feel free to contribute your ideas) as their converter should overrule our custom converter in `trexio-tools` in the nearest future.

**Closed by q-posev** 2024-11-13 08:18 UTC
Labels: bug
